required = ["github.com/onsi/ginkgo/ginkgo"]

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"
