required = ["github.com/onsi/ginkgo/ginkgo"]

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  branch = "master"
  name = "code.cloudfoundry.org/filelock"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[override]]
  source = "https://github.com/fsnotify/fsnotify/archive/v1.4.7.tar.gz"
  name = "gopkg.in/fsnotify.v1"
